### ISSUE TITLE
Issue with Exterior Facet Indices in Tutorial 1

### ISSUE THREAD

**Issue by slavakung** [jorgensd/dolfinx-tutorial#100]
Hello

I am trying to follow:
https://jorgensd.github.io/dolfinx-tutorial/chapter1/fundamentals_code.html

However, I get:

>>> boundary_facets = mesh.exterior_facet_indices(domain.topology)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dolfinx.mesh' has no attribute 'exterior_facet_indices'

After some digging I found there is an alternative version of this function:

>>> boundary_facets = mesh.compute_boundary_facets(domain.topology)

However after continuing apparently it does not quite do the same things, and I obtain a significant error in the solution:

>>> if domain.comm.rank == 0:
...     print(f"Error_L2 : {error_L2:.2e}")
...     print(f"Error_max : {error_max:.2e}")
... 
Error_L2 : 7.55e+00
Error_max : 1.06e+01

Suggestions?

**Comment by jorgensd** [comment]
What version of DOLFINx are you running?
Please print `dolfinx.__version__`

**Comment by slavakung** [comment]
0.4.1
