### ISSUE TITLE
Issue on page /chapter1/fundamentals_code.html

### ISSUE THREAD

**Issue by jacoboglez** [jorgensd/dolfinx-tutorial#103]
The definition of the linear part of the equation
`L = f * v * ufl.dx`
causes the following error when the problem is solved `uh = problem.solve()`:
`ArityMismatch: Failure to conjugate test function in complex Form`

It can be solved by changing the aforementioned definition of the linear part by
`L = ufl.inner(f,v) *ufl.dx`

**Comment by jorgensd** [comment]
The problem described in the first section is meant to be executed in real mode, as the source and boundary conditions are real valued functions. 
there is a separate section in solving complex valued problems at: https://jorgensd.github.io/dolfinx-tutorial/chapter1/complex_mode.html
