### ISSUE TITLE
Issue on chapter2/ns_code2.html

### ISSUE THREAD

**Issue by dajuno** [jorgensd/dolfinx-tutorial#105]
"As we have used an explicit approximation of the non-linear term we only have to assemble the matrix once, but we have to save the two previous solutions."

It's a (semi-)implicit formulation and the matrix is reassembled at every time step. This is correct in the code example.

**Comment by jorgensd** [comment]
This error crept in when I rewrote the schemes for improved stability: https://github.com/jorgensd/dolfinx-tutorial/pull/99
