### ISSUE TITLE
Velocity and pressure can't be showed in paraview.

### ISSUE THREAD

**Issue by jiangzhangze** [jorgensd/dolfinx-tutorial#107]
I computed a flow around cylinder as [https://github.com/jorgensd/dolfinx-tutorial/blob/v0.4.0/chapter2/ns_code2.ipynb](url).The info showed the the computation have completed and I can find the xdmf file in the folder:
![image](https://user-images.githubusercontent.com/99314760/204711139-95c122ec-71e1-45db-b123-c2548aa16488.png).
But mesh is showed only in paraview without p and v:
![image](https://user-images.githubusercontent.com/99314760/204718759-f3793ed1-7645-497d-94bc-d24fb3d203f7.png)

**Comment by jorgensd** [comment]
You need to use the `ExtractBlock` filter to get either variable.

**Comment by jiangzhangze** [comment]
Hi @jorgensd :
I add an ExtractBlock as [https://jorgensd.github.io/dolfinx-tutorial/chapter1/membrane_paraview.html?highlight=paraview](url),but I can't find the p：
![image](https://user-images.githubusercontent.com/99314760/204739198-b33bb38b-67e4-4ed6-bae0-65fba0073f01.png)
 In addition,in most of time steps, the velocity of computaion domain can't perform as expcted especially after 4900 step（total is 12800）：
![image](https://user-images.githubusercontent.com/99314760/204740318-12542683-fbe2-4ddd-ae33-ad07ec0e5d76.png)
![image](https://user-images.githubusercontent.com/99314760/204740423-a84f4b25-ad0f-477d-a910-3e8d1344d1d3.png)
![image](https://user-images.githubusercontent.com/99314760/204740565-e4cd6a30-2479-4a95-9b8c-784f359ad7e7.png)
![image](https://user-images.githubusercontent.com/99314760/204740681-73700ad4-a212-4fe9-8ef0-fa3f6b008616.png)
Are there any suggestions?

**Comment by jorgensd** [comment]
> but I can't find the p：

You need to extract the other block to get `p`.

**Comment by jorgensd** [comment]
For the second bit, I would suggest moving to the 0.5.1 release of the code, as I changed to splitting scheme to improve the stability of the problem: 
https://github.com/jorgensd/dolfinx-tutorial/pull/99
