### ISSUE TITLE
Issue on page /chapter1/fundamentals.html

### ISSUE THREAD

**Issue by gerlja** [jorgensd/dolfinx-tutorial#136]
On the page with title "Solving the Poisson equation" the text after eq. 5 starts with "From literature a(u,v) is known as the bilinear form and L(V) as a linear form."

"L(V)" needs to be replaced by "L(v)" - a small "v" instead of a capital "V".

**Comment by jorgensd** [comment]
Closed with #137. Will be on the webpage once there is a 0.7 release of DOLFINx.
