### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nate-sime** [jorgensd/dolfinx-tutorial#140]
This is (sadly) no longer hosted:

https://github.com/jorgensd/dolfinx-tutorial/blob/main/fem.md?plain=1#L74

**Comment by nate-sime** [comment]
I think the repository shifted since I posted this issue. I'm referring to the line:

```
- [Finite element analysis for coupled problems](https://david-kamensky.eng.ucsd.edu/teaching/mae-207-fea-for-coupled-problems), by David Kamensky.
```

**Comment by jorgensd** [comment]
New link would be: https://drive.google.com/file/d/1o0DY1RWoXd-gOISqyRzJoDHUHvSMvSg3/view?usp=sharing
