### ISSUE TITLE
Issue on page /chapter4/solvers.html

### ISSUE THREAD

**Issue by gerlja** [jorgensd/dolfinx-tutorial#143]
Dear Mr Dokken,

I noticed that the link to the PETSc documentation doesn't work. It's in the paragraph right below the headline "Choosing a linear solver and preconditioner".

Best regards,
Jonathan

**Comment by jorgensd** [comment]
Should be: 
https://petsc.org/release/manual/ksp/#tab-kspdefaults
and 
https://petsc.org/release/manual/ksp/#tab-pcdefaults
with the new webpage layout of petsc
