### ISSUE TITLE
pip install pyvista fail

### ISSUE THREAD

**Issue by gregnordin** [jorgensd/dolfinx-tutorial#144]
The docker image apparently starts without the pyvista package installed and I can't seem to pip install it after starting the docker container. Here is how I start it:

`docker run --init -p 8888:8888 -v "$(pwd)":/root/shared -w /root/shared ghcr.io/jorgensd/dolfinx-tutorial:v0.6.0`

A url is provided from which I get a Jupyter Lab session served by the container. I've attached a zip file containing the notebook I created and from which I try to install pyvista. The errors are quite long so I thought it better to attach the file rather than paste the message here. From #130 it looks like pyvista should be installable. Perhaps I am missing something basic, but I'm stumped so am looking for clues how to fix the problem.

[Test_tutorial_docker_version.ipynb.zip](https://github.com/jorgensd/dolfinx-tutorial/files/12826904/Test_tutorial_docker_version.ipynb.zip)

**Comment by jorgensd** [comment]
As you can see by the output, the issue is that VTK does not supply binaries on modern macs (ref: https://github.com/KitwareMedical/VTKPythonPackage/issues/42). 
@finsberg has made a mac-binary of VTK, which can be installed as described in: https://github.com/KitwareMedical/VTKPythonPackage/issues/42#issuecomment-1611514482

**Comment by gregnordin** [comment]
Thank you very much! Installing the mac-binary of VTK by @finsberg takes care of the problem. I did not know what that error meant so am very appreciative of your help.

Would you like me to submit a small pull request to put this in the documentation so future mac users don't run into the same problem as I did?

**Comment by jorgensd** [comment]
Sure! Make sure you make a pull request against the release branch, as I plan to release a 0.7.0 compatible version soon.
