### ISSUE TITLE
"buttons" for Github and binder(?) not appearing on tutorial pages

### ISSUE THREAD

**Issue by mmoelter** [jorgensd/dolfinx-tutorial#157]
On this page:
https://jsdokken.com/dolfinx-tutorial/
the text indicates the reader can make comments or suggestions by clicking on the GitHub symbol to go to the issue tracker.  

The next section indicates that, as an interactive notebook, the reader can run notebooks by using the Rocket (binder?) symbol. 

As you can see in the screenshot, neither of those "buttons" are showing up.
![Screenshot 2023-11-14 at 4 26 39 PM](https://github.com/jorgensd/dolfinx-tutorial/assets/1598849/4b45d489-7edf-4979-a980-40ee32cfe6b1)

I have visited this tutorial in the past and those buttons **were** present.

**Comment by jorgensd** [comment]
I’ve seen this as well, and I have to figure out what has changed in jupyterbook

**Comment by jorgensd** [comment]
Could be that adding `  baseurl: https://jsdokken.com/` to the html config section works. Will test this once I've got extra time.

**Comment by jorgensd** [comment]
Related to: https://github.com/executablebooks/jupyter-book/issues/2076

**Comment by jorgensd** [comment]
Fixed on main branch

**Comment by mmoelter** [comment]
Thanks for the follow up and fix. I will have a few suggestions for wording/typos in the future.
