### ISSUE TITLE
Typos: Issue on page /index.html

### ISSUE THREAD

**Issue by mmoelter** [jorgensd/dolfinx-tutorial#164]
Paragraph 1, Line 1:
"This webpage gives a concise overview of..."
should be
"These webpages give a concise overview of..."

Paragraph 2, Line 1:
"DOLFINx can be used as either a C++ or Python software..."
should be
"DOLFINx can be used as either C++ or Python software..."

**Comment by jorgensd** [comment]
Dear @mmoelter, thanks for the corrections. I've added them to a pull request that will be merged into the main branch in about 30 minutes.
