### ISSUE TITLE
Issue on page /fem.html

### ISSUE THREAD

**Issue by mmoelter** [jorgensd/dolfinx-tutorial#167]
= 1st paragraph
-- 1st sentence:
...for solving partial differential equations.
should be
...for solving partial differential equations (PDEs).

-- 2nd sentence:
The project was initiated in 2003, and is developed in collaboration between researchers from a number of universities and research institutes around the world.
should be
The project was initiated in 2003, and is developed in a collaboration among researchers from several universities and research institutes around the world.

-- 2nd paragraph, 1st sentence:
The latest version of the FEniCS project, FEniCSx, consists of several building blocks, namely [Basix](https://github.com/FEniCS/basix/), [UFL](https://github.com/FEniCS/ufl), [FFCx](https://github.com/FEniCS/ffcx) and [DOLFINx](https://github.com/FEniCS/dolfinx).

should be (put Dolfinx first to match the order of the following text)

The latest version of the FEniCS project, FEniCSx, consists of several building blocks, [DOLFINx](https://github.com/FEniCS/dolfinx), namely [Basix](https://github.com/FEniCS/basix/), [UFL](https://github.com/FEniCS/ufl), and [FFCx](https://github.com/FEniCS/ffcx).

= "What you will learn"
-- 1st sentence:
...to solve PDEs in FEniCS.
should be
...to solve PDEs using FEniCS.

-- sentence after bulleted list
Important topics involve how...
should be
Important topics include: how...

= "How to use this tutorial"
-- 2nd sentence:
Therefore we will mostly...
should be
Therefore, we will mostly...

= "Obtaining the software"
-- sentence after "Tutorial compatible docker images":
...is available in the [Github Packages](https://github.com/jorgensd/dolfinx-tutorial/pkgs/container/dolfinx-tutorial))
should be (remove parentheses, add period)
...is available in the [Github Packages](https://github.com/jorgensd/dolfinx-tutorial/pkgs/container/dolfinx-tutorial).

-- sentence before heading "Official images":
The tutorials can also be exported as a notebook or PDF by... 
should be
The tutorials can also be exported as an IPython notebook or PDF by...

-- 2nd sentence after heading "Official images":
...one can directly access the image:
should be
...one can directly access the image using:

-- sentence before heading "Installation from source":
If all goes well, no error-messages should appear.
should be
If all goes well, no error messages should appear.

= Introduction to the finite element method
-- 1st sentence:
In the last decade, a wide range of lecture notes on finite elements methods has been made open access. 
should be
In the last decade, several sets of lecture notes on finite element methods have been made open access. 

-- sentence after bulleted list of materials:
There has been written many good text-books on the finite element method, and we refer to the original FEniCS tutorial, for references to these,...
should be
Many good textbooks on the finite element method have been written, and we refer to the original FEniCS tutorial for references to these,...

**Comment by jorgensd** [comment]
@mmoelter Thanks for the suggestions. Your changes in a pull request would be welcomed, then your suggestions will get counted as your contributions.

**Comment by mmoelter** [comment]
Will make a pull request.

Matt

Matthew Moelter
Professor
Department of Physics
California Polytechnic State University
San Luis Obispo, CA 93407

Direct 805-756-2656
***@***.***
https://calpoly.zoom.us/j/8057562656


On Dec 19, 2023, at 11:24 AM, Jørgen Schartum Dokken ***@***.***> wrote:



@mmoelter<https://github.com/mmoelter> Thanks for the suggestions. Your changes in a pull request would be welcomed, then your suggestions will get counted as your contributions.

**Comment by jorgensd** [comment]
@mmoelter Did you want to make this PR? I've seen the other PRs, but they don't seem to have these changes.

**Comment by mmoelter** [comment]
I did it shortly after your suggestion and then it was merged on Dec 20  (#168).
