### ISSUE TITLE
Issue on page /chapter1/fundamentals_code.html : dolfinx.Constant or fem.Constant?

### ISSUE THREAD

**Issue by tyagi-ankit** [jorgensd/dolfinx-tutorial#172]
Under the heading "Defining the source term" it says :  "As the source term is constant over the domain, we use `dolfinx.Constant`".

But the code below uses `fem.Constant`, as in

```python
from dolfinx import default_scalar_type
f = fem.Constant(domain, default_scalar_type(-6))
```
Again, in the callout --- "Compilation speed-up" --- just below,  `dolfinx.Constant` is used. Please clarify.

**Comment by jorgensd** [comment]
Should be updated to `fem.Constant`
