### ISSUE TITLE
Sign of The Navier-Stokes equation test problem 2

### ISSUE THREAD

**Issue by BillMaZengou** [jorgensd/dolfinx-tutorial#173]
Hi,

I am confused by the sign of the Navier-Stokes equation test problem 2.
![image](https://github.com/jorgensd/dolfinx-tutorial/assets/57754488/60a8b889-9172-46bb-b104-a1b983e69f8e)

It seems that the code flips the sign for this two lines. What happens?
![image](https://github.com/jorgensd/dolfinx-tutorial/assets/57754488/9421382c-61de-42d8-80d2-e05315aeb647)

**Comment by jorgensd** [comment]
Sure, But `f` is Zero in this tutorial, so it doesn’t really matter wrt the sign
