### ISSUE TITLE
Issue on page /chapter1/fundamentals_code.html

### ISSUE THREAD

**Issue by phkonzen** [jorgensd/dolfinx-tutorial#175]
Hi,
First, thank you very much for the dolfinx-tutorial. In the first line of the following code region:

```
error_max = numpy.max(numpy.abs(uD.x.array-uh.x.array))
# Only print the error on one process
if domain.comm.rank == 0:
    print(f"Error_L2 : {error_L2:.2e}")
    print(f"Error_max : {error_max:.2e}")
```

Should it be `uex` instead of `uD`, isn't it?

**Comment by jorgensd** [comment]
No, as uex is in a higher order function space, you cannot compare it dof by dof.
ud has the exact solution interpolated into the same space as uh, and is Therefore used for the Max error at vertices
