### ISSUE TITLE
Math subscripts rendered as *  on page /chapter1/nitsche.html

### ISSUE THREAD

**Issue by drew-parsons** [jorgensd/dolfinx-tutorial#178]
There's a typesetting problem with the equations at https://jsdokken.com/dolfinx-tutorial/chapter1/nitsche.html
Subscripts such as `\int_{\Omega}` are getting rendered in the browser (firefox) with a star, as in "∫*Ω" instead of "∫<sub>Ω</sub>".  It makes it look as if some arcane operators are being used, making it seem more complicated than it really is.

The source code at https://github.com/jorgensd/dolfinx-tutorial/blob/1b64530ec5c30911ea5ba330906217d446bcf035/chapter1/nitsche.py#L48 looks fine, so not clear where the problem is.  Perhaps in the sphinx modules used to generate the html pages.

Subscripts on other pages are correctly formatted.

**Comment by jorgensd** [comment]
Good spot. I’ll have a look.

**Comment by drew-parsons** [comment]
missed one in eq.9

**Comment by drew-parsons** [comment]
Eq.10b too (`_` is shown verbatim)
