### ISSUE TITLE
samll equation issue in 'nitsch.ipynb & .py'

### ISSUE THREAD

**Issue by Yanjun96** [jorgensd/dolfinx-tutorial#182]
Hi,
In the Chapter 1, about Weak imposition of Dirichlet conditions for the Poisson problem. The equation (9) and (10) now is:

![Screenshot from 2024-03-25 14-16-15](https://github.com/jorgensd/dolfinx-tutorial/assets/150266564/3556e527-3407-4543-b4cf-07ea740c0aed)

The D should change to below:
![Screenshot from 2024-03-25 15-51-03](https://github.com/jorgensd/dolfinx-tutorial/assets/150266564/ccf9c8ad-8006-48f2-8f89-c0749905474f)

I do not know how to push my changes directly. Maybe I need to find help of git tutorial.

Regards
yanjun

**Comment by jorgensd** [comment]
It should be resolved with the next few PRs. Thanks for reporting it
