### ISSUE TITLE
Issue with `V = fem.FunctionSpace` in Poisson's example

### ISSUE THREAD

**Issue by vyastreb** [jorgensd/dolfinx-tutorial#190]
Hello,

I was trying to get through the first tutorial and in Poisson's example I experienced a problem with the line
```python
V = fem.FunctionSpace(domain, ("Lagrange", 1))
```
I get
```shell
    V = fem.FunctionSpace(domain, ("Lagrange", 1))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FunctionSpace.__init__() missing 1 required positional argument: 'cppV
```
I use
DOLFINx version: 0.8.0 based on GIT commit: 7de5fd34d6b554dd3295198f1778c91bf11afa81 of https://github.com/FEniCS/dolfinx/

So I switched to 
`V = fem.functionspace(domain, ("Lagrange", 1))`
as used in [this demo](https://github.com/FEniCS/dolfinx/blob/main/python/demo/demo_poisson.py).

Thanks!

**Comment by jorgensd** [comment]
Hi @vyastreb 
I'm in the process of updating the tutorial for 0.8.x.
See: https://github.com/jorgensd/dolfinx-tutorial/pull/166

**Comment by vyastreb** [comment]
Hell @jorgensd,
Alright, I see! Thank you for such a prompt reaction!
