### ISSUE TITLE
TypeError: FunctionSpace.__init__() missing 1 required positional argument: 'cppV'

### ISSUE THREAD

**Issue by kangchouapp** [jorgensd/dolfinx-tutorial#228]
`Traceback (most recent call last):
  File "/home/ovo/myapp2024/myFEniCS/demo.py", line 15, in <module>
    V = dolfinx.fem.FunctionSpace(mesh, c_el)
TypeError: FunctionSpace.__init__() missing 1 required positional argument: 'cppV'`

Traceback (most recent call last):
  File "/home/ovo/myapp2024/myFEniCS/demo.py", line 15, in <module>
    V = dolfinx.fem.FunctionSpace(mesh, c_el)
TypeError: FunctionSpace.__init__() missing 1 required positional argument: 'cppV'

**Comment by jorgensd** [comment]
Use `dolfinx.fem.functionspace`. See https://github.com/jorgensd/dolfinx-tutorial/blob/main/Changelog.md#v080
