### ISSUE TITLE
fundamentals_code code block mislocated

### ISSUE THREAD

**Issue by matsievskiysv** [jorgensd/dolfinx-tutorial#28]
It seems that code block in [fundamentals_code](https://jorgensd.github.io/dolfinx-tutorial/chapter1/fundamentals_code.html) related to the L2 error computation is mislocated.
![2021-04-18_23-09](https://user-images.githubusercontent.com/26824900/115159334-50bef900-a09b-11eb-8946-e85a403decec.png)

Additionally, if there's a `First, we compute...`, there should probably be `Second, we compute...`.

**Comment by jorgensd** [comment]
Fixed
