### ISSUE TITLE
Parallel `Function` evaluation and `GhostMode.shared_facet` 

### ISSUE THREAD

**Issue by godsic** [jorgensd/dolfinx-tutorial#31]
I am trying to evaluate function in parallel like demonstrated in [Chapter 1](https://jorgensd.github.io/dolfinx-tutorial/chapter1/membrane_code.html#making-curve-plots-throughout-the-domain) of the tutorial and, then, `Gatherv` on `rank 0`
```python
    bbox_tree = dolfinx.geometry.BoundingBoxTree(mesh, mesh.geometry.dim)

    pts = np.vstack(np.meshgrid(xx, yy, [z])).reshape(3, -1).T
    cells = []
    pts_on_proc = []
    for pt in pts:
        cell_candidates = dolfinx.geometry.compute_collisions_point(
            bbox_tree, pt)
        cell = dolfinx.geometry.select_colliding_cells(
            mesh, cell_candidates, pt, 1)
        if len(cell) == 1:
            pts_on_proc.append(pt)
            cells.append(cell[0])

    q_vals_on_proc = Q.eval(pts_on_proc, cells)

    val_counts = np.array(
        MPI.COMM_WORLD.gather(q_vals_on_proc.size, root=0))

    if MPI.COMM_WORLD.rank == 0:
        q_vals = np.empty(sum(val_counts), dtype=np.float64)
    else:
        q_vals = None

    MPI.COMM_WORLD.Gatherv(sendbuf=q_vals_on_proc, recvbuf=(
        q_vals, val_counts), root=0)
```
Eventually I end up with more values than grid points. This makes me think that `GhostMode.shared_facet` leads to a given point residing on multiple ranks. Is it a bug or intended behavior?

**Comment by jorgensd** [comment]
There are two possible reasons for having the same point on multiple processes:
1. The point is on the process boundary
2. The point is in a cell owned by one process, and this cell is a ghost on the other process.

The first case is hard to put up safeguards for, as it would require global communication per point (allgather of a boolean/int indicating if it is on a boundary).
You can add a safeguard against the second case by adding an additional check before adding the point to `pts_on_proc`. 
This would be checking that `cell<mesh.topology.index_map(mesh.topology.dim).size_local`, i.e only adding the cell to the list if it is owned by the process.

**Comment by jorgensd** [comment]
Such a condition is for instance used in my `dolfinx_mpc` code: https://github.com/jorgensd/dolfinx_mpc/blob/58855754d7b36bbc8e65c2e5f288a9fb4473fd62/python/dolfinx_mpc/periodic_condition.py#L52-L54

**Comment by jorgensd** [comment]
Points can reside on multiple process, as

**Comment by godsic** [comment]
@jorgensd Thanks for in-deep explanation. Now it makes me think that making sub-domain around plane-of-interest with `GhostMode.none` and projecting on it will make your snippet universally work without extra safeguards. Or am I missing something?

**Comment by godsic** [comment]
Nevermind, I ended up `Gatherv` points coordinates, removing duplicates with `np.unique(...)` and then used obtained unique indices to filter out function values. This should have all corner cases covered.
