### ISSUE TITLE
TypeError in Fundamentals Code with latest dolfinx

### ISSUE THREAD

**Issue by tfoutz99** [jorgensd/dolfinx-tutorial#41]
I get a typeerror in chapter 1 fundamentals_code.ipynb at cell 14:

`
import dolfinx.plot; 
topology, cell_types = dolfinx.plot.create_vtk_topology(mesh, mesh.topology.dim)
`

The error seems to be with the mesh type.

TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_101/4156726744.py in <module>
      1 import dolfinx.plot
----> 2 topology, cell_types = dolfinx.plot.create_vtk_topology(mesh, mesh.topology.dim)

/usr/lib/python3.9/functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

/usr/local/dolfinx-real/lib/python3.8/dist-packages/dolfinx/plot.py in create_vtk_topology(mesh, dim, entities)
     76 
     77     # Array holding the cell type (shape) for each cell
---> 78     e_type = cpp.mesh.cell_entity_type(mesh.topology.cell_type, dim)
     79     degree = _element_degree(e_type, geometry_entities.shape[1])
     80     if degree == 1:

TypeError: cell_entity_type(): incompatible function arguments. The following argument types are supported:
    1. (arg0: dolfinx.cpp.mesh.CellType, arg1: int, arg2: int) -> dolfinx.cpp.mesh.CellType

Invoked with: <CellType.quadrilateral: -4>, 2

**Comment by jorgensd** [comment]
This will be fixed tomorrow when the docker images have been rebuilt, as i’ve already pushed a fix for this in the repo.

**Comment by jorgensd** [comment]
Fixed
