### ISSUE TITLE
Typo in "Solving the Poisson equation"?

### ISSUE THREAD

**Issue by giovap95** [jorgensd/dolfinx-tutorial#73]
Hi, 
I think there may be a typo in equation 2, where trial and test space are defined, in the tutorial [Solving the Poisson equation](https://jorgensd.github.io/dolfinx-tutorial/chapter1/fundamentals.html)

V should contain the variable u, not v. 
Bye,
Giovanni

**Comment by jorgensd** [comment]
As you can see in the text, V and hat V differs by the choice of boundary conditions. 
this is how one usually defines the spaces mathematically. 
In numerical implementations, DirichletBCs are handled differently, as explained in the following page of the tutorial. In that case, the test and trial function is picked to be in the same space.
