### ISSUE TITLE
Dockerfile dolfinx/lab not able to run (em) tutorial? 

### ISSUE THREAD

**Issue by gsteele13** [jorgensd/dolfinx-tutorial#74]
First, awesome project and great tutorials! Very excited to get this running!

For now, I'm running from the docker image: 

docker run -p 8888:8888 dolfinx/lab

I ran into a few issues though: first, `pythreejs` needed to be installed:

```
root@b8715fff55a6:~# pip install pythreejs
```

which I did inside a terminal in the JL interface, after which I could load the library, but then got errors "model cannot be found". 

My guess is that the JL instance needs to be restarted after the package is installed, but I'm a bit of a docker noob and cannot figure out how to do this: if I stop the container and restart, there is no persistance of the changes I made...

I'll probably go whole-hog and install things properly in a conda env for now. But I guess probably there is a relatively simple fix in configuring the dolfinx/lab docker image? 

Cheers,.
Gary

**Comment by jorgensd** [comment]
I would suggest you follow the instructions in: https://github.com/jorgensd/dolfinx-tutorial#docker-images
Specifically, clone the git repository and run:
```bash
cd docker
docker build -f LocalDockerfile -t local_lab_env .
```
and  then you can start a container with
```bash
 docker run --rm -ti -v $(pwd):/root/shared -w /root/shared  --init -p 8888:8888 local_lab_env
```
