### ISSUE TITLE
Link to Gmsh tutorial not working 

### ISSUE THREAD

**Issue by keiyamamo** [jorgensd/dolfinx-tutorial#83]
Hi @jorgensd ,

Thank you for creating a really good tutorial!
I just noticed that this link http://jsdokken.com/converted_files/tutorial_gmsh.html  is not working. 
Maybe it is just not ready to be published but thought it would be nice to report. 

Best,
Kei

**Comment by jorgensd** [comment]
I've updated the link, as I rewrote some pages on my webpage some weeks back
