### ISSUE TITLE
Docker image Error displaying widget: model not found

### ISSUE THREAD

**Issue by TeaCult** [jorgensd/dolfinx-tutorial#84]
First time using docker and first time trying fenics. 
I have followed instructions on ubuntu 22.04 and then installed on docker host : 

It didn't worked out of box I installed these on the host: 
Then I ve got topology cell_types and geometry. Basic functionality seems to be working. 

```
    pip3 install vtk
    pip3 install pythreejs
    pip3 install ipympl 
```

Everythings works fine except pyvista drawing. 

Both first time on fenics and docker. 

Tried to adjust versions in jupyter extension list 
I adjusted some version it asked me to intall npm and node js installed it with 
```
! apt-get install -y npm  # in docker images jupyter lab. Then it wanted me to rebuild lab 
! jupyter lab rebuild 
```

then it started to complaining abotu pythreejs although it is installed ... 

I am now installing latest version of all of extensions ... and rebuilding the lab. 
functionality is ok but display is no go. 
I wonder what if I use something like open3D to display it. I used it with google colab before. 

Do you have any suggestion ?
I was trying first tutorial in online docs of fenicsx. 

Thank you.

**Comment by jorgensd** [comment]
There is currently an issue with pyvista and python3.10/VTK compatibility, see: https://github.com/pyvista/pyvista/pull/2912

For now, i would suggest using the docker image: `dokken92/dolfinx_custom:16062022` as explained in https://jorgensd.github.io/dolfinx-tutorial/fem.html#tutorial-compatible-docker-images

**Comment by TeaCult** [comment]
Thank you very much. I missed this tutorial compatible image section.
