### ISSUE TITLE
provide tutorial for the dolfinx release version

### ISSUE THREAD

**Issue by drew-parsons** [jorgensd/dolfinx-tutorial#87]
The formatted tutorial at https://jorgensd.github.io/dolfinx-tutorial/ corresponding to the development version of dolfinx from git HEAD.

This makes the tutorial difficult to follow for people using the release version of dolfinx, since HEAD diverges rapidly from the last release. 

Is it possible to configure a formatted version of the tutorial for the release version(s)?, e.g. at https://jorgensd.github.io/dolfinx-tutorial/0.4.1 or https://jorgensd.github.io/dolfinx-tutorial/v0.4.1  (if tracking the dolfinx release version). 

The analogy could be with the numpy docs, which provide versioned docs, e.g. https://docs.scipy.org/doc/numpy-1.17.0/user/

**Comment by jorgensd** [comment]
To be able to do so, I would need to set up `jupyterbook` with readthedocs (https://jupyterbook.org/en/stable/publish/readthedocs.html), which was not possible when the previous version was released, as DOLFINx was not installable through `pip` or `conda`. Now, that is possible to installed DOLFINx through `pip` or `conda` it should be possible to do it.

However, I do not have a time-line as to when I have bandwidth to have another go at this.

The most preferable thing would be to only update the tutorial at a new release. However, I couldn't do this for the current release, as there were some severe limitations to the docker images shipped with the release.

**Comment by drew-parsons** [comment]
Thanks.  I guess it will asymptote to smoothness in any case with less divergence between release and HEAD over time.

**Comment by jorgensd** [comment]
this is what is done now, documentation is published on release.
